[versions]
shadow = "8.3.5"
spotless = "6.25.0"
okhttp = "3.14.9"
gson = "2.11.0"
spigot = "1.8.8-R0.1-SNAPSHOT"
socketclient = "2.1.1"
lombok = "1.18.36"
skript = "2.9.4"
json = "20240303"
okio = "1.17.6"

[plugins]
shadow = {id = "com.gradleup.shadow", version.ref = "shadow"}
spotless = {id = "com.diffplug.spotless", version.ref = "spotless"}

[libraries]
okhttp = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}
spigot = {group = "org.spigotmc", name = "spigot-api", version.ref = "spigot"}
socketclient = {group = "io.socket", name = "socket.io-client", version.ref = "socketclient"}
lombok = {group = "org.projectlombok", name = "lombok", version.ref = "lombok"}
skript = {group = "com.github.SkriptLang", name = "Skript", version.ref = "skript"}
json = {group = "org.json", name = "json", version.ref = "json"}
okio = {group = "com.squareup.okio", name = "okio", version.ref = "okio"}